name: Testing Github Actions
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Test Application
        run: |
          chmod +x test.sh
          ./test.sh
