name: Testing Github Actions
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Test Application
        run: |
          chmod +x test.sh
          ./test.sh
  
  
  
  
 
  
  
    runs-on: ubuntu-22.04
    steps:
      - name: My First Actions
        run: touch file.txt
      - name: My Second Actions
        run: echo "Some Data" > file.txt
      - name: My Third Actions
        run: cat file.txt
  my_second_job:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Directory Listing
        run: ls -la