name: Run Python File
on:
  workflow_dispatch:
jobs:
  run_python_app:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/checkout@v4
      - name: Create Environment
        run: python -m venv .venv
      - name: Enable Environment
        run: source ./.venv/bin/activate
      - name: Install Libraries
        run: pip install -r requirements.txt
      - name: Run Programm
        run: python app.py