name: Django CI/CD
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
env:
  DJANGO_SECRET_KEY: sf8d84098trfewfc0s8w048e7fs98d67gfsd786df8s56df8675df
  DJANGO_DEBUG: False
  DB_ENGINE: django.db.backends.mysql
  DB_NAME: django
  DB_USER: root
  DB_PASSWORD: secret
  DB_HOST: db
  DB_PORT: 3306
jobs:
  test_django:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v4
      - name: Create Environment File
        run: |
          echo "DJANGO_SECRET_KEY=${{env.DJANGO_SECRET_KEY}}" >> .env
          echo "DJANGO_DEBUG=${{env.DJANGO_DEBUG}}" >> .env
          echo "DB_ENGINE=${{env.DB_ENGINE}}" >> .env
          echo "DB_NAME=${{env.DB_NAME}}" >> .env
          echo "DB_USER=${{env.DB_USER}}" >> .env
          echo "DB_PASSWORD=${{env.DB_PASSWORD}}" >> .env
          echo "DB_HOST=${{env.DB_HOST}}" >> .env
          echo "DB_PORT=${{env.DB_PORT}}" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{env.DB_PASSWORD}}" >> .env
          echo "MYSQL_DATABASE=${{env.DB_NAME}}" >> .env
      - name: Start Containers
        run: docker compose up -d
      - name: Wait for Containers Start
        run: sleep 30
      - name: Run Tests
        run: docker compose exec -T web python manage.py test 
  delivery:
    runs-on: 'ubuntu-22.04'
    needs: test_django
    steps:
      - name: Apply Changes
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: lesson.lv
          username: teacher 
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          fingerprint: SHA256:oOrrFGkhFJ2fRqqzc+YJvBN2B3fPnvquUpFaL1V1mXA
          script: |
            cd django-teacher
            git pull
            docker compose down
            docker compose up -d --build
            docker image prune --force